Repository anoma/juvix-docs, pull requests merged in 2023-06, with the labels that each got.

#22 Add a section about iterators to the tutorial
  docs/tutorials/learn.juvix
  docs/tutorials/learn.md
Labels: documentation

#5 Add documentation for local modules and projects
  docs/reference/language/infix.md
  docs/reference/language/modules.md
  docs/reference/language/modules_old.md
  docs/reference/language/project.md
  docs/reference/language/statement.md
Labels: reference

#24 Fix the 'sum' example in the tutorial
  docs/reference/language/modules.md
  docs/reference/language/modules_old.md
  docs/reference/language/statement.md
  docs/tutorials/learn.juvix
Labels: bug

#30 Iterators reference
  docs/reference/language/iterators.md
Labels: enhancement

#34 Fix wrong -e header in fetch files
  Makefile
Labels: enhancement

#37 Solutions to exercises in the tutorial
  docs/tutorials/learn.juvix
  docs/tutorials/learn.md
Labels: enhancement

#39 Fix the quickstart guide
  docs/howto/quick-start.md
  docs/index.md
  docs/tutorials/learn.md
Labels: enhancement

#40 Small improvements to the 'Compilation' how-to guide
  docs/howto/compilation.md
Labels: enhancement

#41 Add minor improvements to the docs
  docs/explanations/totality/termination.md
  docs/howto/compilation.md
  docs/howto/installing.md
  docs/notes/runtime-benchmark-results.md
  docs/reference/examples.md
  docs/reference/judoc.md
  docs/reference/language/comments.md
  docs/reference/language/control.md
  docs/reference/language/datatypes.md
  docs/reference/language/functions.md
  docs/reference/language/modules.md
  docs/reference/language/project.md
  docs/reference/tooling/CLI.md
  docs/reference/tooling/emacs.md
  docs/reference/tooling/testing.md
Labels: documentation

#50 Iterators blog post
  docs/blog/posts/iterators.md
Labels: blog

#49 Add warmup exercises
  docs/tutorials/learn.juvix
  docs/tutorials/learn.md
Labels: documentation

#52 VampIR compilation blogpost
  docs/blog/posts/iterators.md
  docs/blog/posts/vampir-circuits.md
Labels: blog

#54 Fix typos in Vamp-IR blogpost
  docs/blog/posts/vampir-circuits.md
Labels: blog

#56 Small improvements to the VampIR blogpost
  docs/blog/posts/vampir-circuits.md
Labels: blog

#55 Add Talks page with the links to the videos
  docs/about/talks.md
  docs/index.md
Labels: video

#60 Update VampIR blogpost
  docs/blog/posts/vampir-circuits.md
Labels: blog

#61 Add blog link on the front page
  docs/index.md
Labels: bug, documentation, blog

#62 Insert newline between links
  docs/index.md
Labels: bug

#64 Update iterators.md
  docs/reference/language/iterators.md
Labels: bug
