Repository anoma/juvix-docs, pull requests merged in 2023-11, with the labels that each got.

#86 Update project documentation for Package.juvix
  .pre-commit-config.yaml
  VERSION
  docs/Package.juvix
  docs/blog/posts/geb-backend/Package.juvix
  docs/blog/posts/geb-backend/juvix.lock.yaml
  docs/blog/posts/geb-backend/juvix.yaml
  docs/blog/posts/strictly-positive-data-types/Package.juvix
  docs/blog/posts/strictly-positive-data-types/juvix.lock.yaml
  docs/blog/posts/strictly-positive-data-types/juvix.yaml
  docs/blog/posts/vampir-circuits/Package.juvix
  docs/blog/posts/vampir-circuits/juvix.yaml
  docs/howto/compilation/CLI.yaml
  docs/howto/compilation/Package.juvix
  docs/howto/compilation/juvix.yaml
  docs/howto/project.md
  docs/howto/project/Package.juvix
  docs/howto/project/ex1/Package.juvix
  docs/howto/project/ex2/Package.juvix
  docs/index/IntentExample.juvix
  docs/index/Package.juvix
  docs/index/juvix.lock.yaml
  docs/index/juvix.yaml
  docs/juvix-packages/Package.juvix
  docs/juvix-packages/juvix.lock.yaml
  docs/juvix-packages/juvix.yaml
  docs/juvix.yaml
  docs/reference/language/Package.juvix
  docs/reference/language/juvix.yaml
  docs/tutorials/Package.juvix
  docs/tutorials/juvix.yaml
Labels: documentation

#80 Add support for juvix-standalone code blocks
  .gitignore
  docs/assets/css/highlight.css
  docs/assets/css/juvix-highlight.css
  docs/assets/css/juvix-highlighting.css
  docs/assets/css/source-macchiato.css
  docs/assets/js/juvix-highlight.js
  docs/reference/language/builtins.juvix
  docs/reference/language/builtins.juvix.md
  docs/reference/language/builtins.md
  mkdocs.yml
  requirements.txt
Labels: backend:markdown

#97 Fix look and feel issues
  docs/assets/css/extra.css
  docs/assets/css/juvix-highlighting.css
  docs/assets/js/highlight.js
  mkdocs.insiders.yml
  mkdocs.yml
Labels: enhancement, fix:bug
